2018-09-02 15:50:02 : noaa_historical :INFO : Getting report ... 
2018-09-02 15:50:03 : noaa_historical :ERROR : Critical error
Traceback (most recent call last):
  File "C:\Users\RobMartin\Desktop\100-days-of-code\exercises\creek\procedural\noaa_historical.py", line 141, in <module>
    count = data['metadata']['resultset']['count']
KeyError: 'metadata'
2018-09-02 15:57:41 : noaa_historical :INFO : Getting report ... 
2018-09-02 15:59:43 : noaa_historical :INFO : Getting report ... 
2018-09-02 16:00:16 : noaa_historical :INFO : Getting report ... 
2018-09-02 16:07:45 : noaa_historical :INFO : Getting report ... 
2018-09-02 16:07:45 : noaa_historical :ERROR : API Call Failed
Traceback (most recent call last):
  File "C:\Users\RobMartin\Desktop\100-days-of-code\exercises\creek\procedural\noaa_historical.py", line 74, in setupRequest
    r.raise_for_status()
  File "C:\Users\RobMartin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.ncdc.noaa.gov/cdo-web/api/v2/data?stationid=GHCND%3AUSC00214884&datasetid=GHCND&datatypeid=PRCP&datatypeid=TMAX&datatypeid=SNOW&datatypeid=SNWD&startdate=2018-08-01&enddate=2018-08-31&units=standard&limit=250&offset=1
2018-09-02 16:08:56 : noaa_historical :INFO : Getting report ... 
2018-09-02 16:08:56 : noaa_historical :INFO : Grabbing 1 through 118 of 118 records
2018-09-02 16:08:56 : noaa_historical :INFO : Writing rows to the database
2018-09-02 16:08:57 : noaa_historical :INFO : Finished writing to database.
Completed 118 records
2018-09-02 20:37:04 : noaa_historical :INFO : Getting report ... 
2018-09-02 20:37:05 : noaa_historical :INFO : Grabbing 1 through 122 of 122 records
2018-09-02 20:37:05 : noaa_historical :INFO : Writing rows to the database
2018-09-02 20:37:05 : noaa_historical :INFO : Finished writing to database.
Completed 122 records
